/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class windows_LastErrorException */

#ifndef _Included_windows_LastErrorException
#define _Included_windows_LastErrorException
#ifdef __cplusplus
extern "C" {
#endif
#undef windows_LastErrorException_serialVersionUID
#define windows_LastErrorException_serialVersionUID -3042686055658047285i64
#undef windows_LastErrorException_serialVersionUID
#define windows_LastErrorException_serialVersionUID -3387516993124229948i64
#undef windows_LastErrorException_serialVersionUID
#define windows_LastErrorException_serialVersionUID -7034897190745766939i64
#undef windows_LastErrorException_serialVersionUID
#define windows_LastErrorException_serialVersionUID 1i64
/*
 * Class:     windows_LastErrorException
 * Method:    retrieveErrorDescription
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_windows_LastErrorException_retrieveErrorDescription
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
